baseURL: "https://samsonajadalu.com/"
languageCode: en-us
title: "Samson Ajadalu"
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enhanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Samson Ajadalu"
    subtitle: "Hello 👋 I’m Samson Ajadalu, a tech enthusiast passionate about solving problems with AI. As an aspiring AI engineer, I use technology to make a real impact. My mornings kick off at the gym, and the rest of the day, I’m deep into coding and working on exciting projects. I like to unwind in the evening by reading or doing research to stay sharp. Let’s connect and create something awesome together!"
    imageUrl: "home/casual-small-square.jpeg"
    imageWidth: 220
    imageHeight: 220

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:samson@samsonajadalu.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/samson-ajadalu/"
    - name: "github"
      url: "https://github.com/SamsonAjadalu"
    - name: "X"
      url: "https://x.com/samsonajadalu"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
